version: '3'
volumes:
  postgres_data: {}

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.aim-app
    depends_on:
      - db
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.aim-web
    depends_on:
      - app
    ports:
      - 3000:3000
      #- 80:80