databases:
  - name: aim_mini_test_postgresql
    databaseName: aim_mini_test_postgresql
    user: wondman_
    region: singapore

services:
  - type: web
    name: aim_mini_test_postgresql
    env: ruby
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: <%= ENV['DATABASE_URL'] %>
        fromDatabase:
          name: aim_mini_test_postgresql
          property: connectionString
      - key: <%= ENV['RAILS_MASTER_KEY'] %>
        sync: false