version: 2.1

# このプロジェクトで実行するジョブの定義
jobs:
  build:
   steps:
      - run: echo "this is the build job"
      - run: echo $DOCKERHUB_PASSWORD
      - run: echo DOCKERHUB_PASSWORD
    docker:
      - image: aim-mini-test:latest
        auth:
          username: dockermy7777
          password: DOCKERHUB_PASSWORD  # コンテキスト/プロジェクト UI 環境変数の参照
    steps:
      - checkout
      - run: echo "this is the build job"
      - run: echo $DOCKERHUB_PASSWORD
  test:
    docker:
      - image: aim-mini-test:latest
        auth:
          username: dockermy7777
          password: $DOCKERHUB_PASSWORD  # コンテキスト/プロジェクト UI 環境変数の参照
    steps:
      - checkout
      - run: echo "this is the test job"

# ジョブの実行順の指定
workflows:
  build_and_test:
    jobs:
      - build
      - test