version: 2.1

# このプロジェクトで実行するジョブの定義
jobs:
  build:
    docker:
      - image: dockermy7777/aim-mini-test:v2
        auth:
          username: dockermy7777
          password: $DOCKERHUB_PASSWORD  # コンテキスト/プロジェクト UI 環境変数の参照
    steps:
      - checkout
      - run: echo "これはbuild job"
  test:
    docker:
      - image: dockermy7777/aim-mini-test:v2
        auth:
          username: dockermy7777
          password: $DOCKERHUB_PASSWORD  # コンテキスト/プロジェクト UI 環境変数の参照
    steps:
      - checkout
      - run: echo "これはtest job"
  deploy_to_render:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: Deploy to Render.com
          command: |
            curl -X POST "https://render.com/api/v1/projects/$RENDER_ACCOUNT_ID/$RENDER_PROJECT_ID/deploy/$RENDER_BRANCH" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            --data '{"branch":"'"$CIRCLE_BRANCH"'", "commit_sha":"'"$CIRCLE_SHA1"'"}'
    when: on_success

# ジョブの実行順の指定
workflows:
  build_and_test:
    jobs:
      - build
      - test
  deploy:
    jobs:
      - deploy_to_render:
          context: render