version: 2.1

# このプロジェクトで実行するジョブの定義
jobs:
  build:
    docker:
      - image: dockermy7777/aim-mini-test:v3
        auth:
          username: dockermy7777
          password: $DOCKERHUB_PASSWORD  # コンテキスト/プロジェクト UI 環境変数の参照
    steps:
      - checkout
      - run: echo "これはbuild job"
  test:
    docker:
      - image: dockermy7777/aim-mini-test:v3
        auth:
          username: dockermy7777
          password: $DOCKERHUB_PASSWORD  # コンテキスト/プロジェクト UI 環境変数の参照
    steps:
      - checkout
      - run: echo "これはtest job"

# ジョブの実行順の指定
workflows:
  build_and_test:
    jobs:
      - build
      - test